theme: jekyll-theme-minimal
title: Sergio López-Sancio
description: I am a PhD candidate in Psycholinguistics at the University of the Basque Country (UPV/EHU).
logo: [https://avatars3.githubusercontent.com/u/37000589?s=400&v=4]
